### ISSUE TITLE
Xorg chooses wrong resolution on AMD Radeon R9 390x with dual display

### ISSUE THREAD

**Issue by girivs** [mattmacy/freebsd-ports-graphics#16]
I have a 1440p monitor on DP-1 and a HTC Vive on HDMI-1. With no Xorg.conf, it goes into very low resolution mode - my feeling is that it's wrongly reading the EDID of the Vive for my primary display. If I disconnect the Vive, it goes into 1440p automatically.

**Comment by mattmacy** [comment]
It appears that DRM will now pick the lowest resolution so that everything that can be shown on one display can be shown on the others. For most people this seems to be a regression with respect to 3.8. When less critical issues have been dealt with I'll figure out how to deal with it.

**Comment by mattmacy** [comment]
You can normally pick the right resolution with Xrandr. You might try amdgpu.

**Comment by girivs** [comment]
Thanks Matt. This is not blocking in anyway since there are ways to get the correct resolution and I don't have the radeon card anymore. I think this can be closed.
