### ISSUE TITLE
EGL defaults to swrast_dri, should be i965_dri.

### ISSUE THREAD

**Issue by johalun** [mattmacy/freebsd-ports-graphics#22]
Setup:
Intel CherryTrail
Ports from xserver-mesa-next with DRI3 enabled.
Sway running.

$ setenv MESA_DEBUG 1; setenv LIBGL_DEBUG verbose; setenv EGL_LOG_LEVEL debug
$ weston-simple-egl (or any other egl application, start from ssh login because we don't have a working wayland terminal emulator yet.) 

Results: 
The app loads swrast driver. Can be confirm by debug output or that 4 extra rendering threads are created (view in 'top').

Fix:
Rebuild libEGL port but make the following change to libGL/Makefile.common
- ALL_DRI_DRIVERS=I915 I965 R200 RADEON SWRAST
+ ALL_DRI_DRIVERS=I915 I965 

Install package
Restart sway
Start egl app

Now using hardware rendering (i965_dri.so is loaded).

**Comment by valpackett** [comment]
> we don't have a working wayland terminal emulator yet

weston-terminal actually worked with the old version of sway, before i ported the new one. The new one works with apps that use newer wayland protocols — so the wayland port is out of date

**Comment by johalun** [comment]
It works now in the xserver-mesa-next-udev branch. Wayland/Weston patches have been redone to use udev and epoll-shim so we can reduce diff to Linux code.  There are still some stuff missing so weston clients can behave weird when terminated in unexpected ways.

**Comment by valpackett** [comment]
Wow, thanks for the updates! Weston works fine, sway (upstream) works… uh… with constant high CPU usage, Way Cooler works fine (and it's wlc based too, so what's the deal with sway even…)

Haven't seen any kqflx hangs!! Also sysmouse evdev landed, so I guess Wayland is usable as a daily desktop :)

**UPD** weston often gets into a state when it's repeatedly spamming the console with messages about **signalfd reading failing** (and it becomes impossible to switch vts even, but normal acpi shutdown works). Maybe sway's high cpu usage is related to this too?

**Comment by mattmacy** [comment]
Probably related - @johalun what is it using for signalfd?

**Comment by valpackett** [comment]
https://github.com/jiixyj/epoll-shim/blob/master/src/signalfd.c

**Comment by johalun** [comment]
epoll-shim probably need some love, could be it. But, the high cpu usage could be software rendering as well? Confirm that EGL is not loading swrast_dri driver..

**Comment by johalun** [comment]
Seems like udev update fixed this.

**Comment by valpackett** [comment]
The default driver? Yeah, my system loads i965 always.
